# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  A5_config = debug
endif
ifeq ($(config),release)
  A5_config = release
endif

PROJECTS := A5

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

A5:
ifneq (,$(A5_config))
	@echo "==== Building A5 ($(A5_config)) ===="
	@${MAKE} --no-print-directory -C build -f Makefile config=$(A5_config)
endif

clean:
	@${MAKE} --no-print-directory -C build -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   A5"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"